### ISSUE TITLE
 Local Editing

### ISSUE THREAD

**Issue by jly0810** [Dongjiahua/VICA-NeRF#4]
I couldn't find the partial editing code and implementation you provided. Can you provide the relevant code and data. And I noticed that some of the results in the paper did not use local editing, why is that? In theory, for editing tasks of key objects in a scene, keeping the background unchanged can improve the results. Thank you！

**Comment by Dongjiahua** [comment]
All the results in the paper do not use local editing except for the local editing section. We don't plan to release the local editing code because local editing is just an exploration in the experiment section, not our main method. In addition, there are already some great local editing implementations, e.g., [GaussianEditor](https://github.com/buaacyw/GaussianEditor).
