### ISSUE TITLE
Doubt about reprojection algorithm

### ISSUE THREAD

**Issue by jbu5105** [Dongjiahua/VICA-NeRF#8]
Hi!

Thank you very much for your work. The reprojection algorithm is very elegant. I get the forward and backward projection in order to account for occlusions. However there is a basic questions that comes to my mind when seeing the reprojection algorithm.

When you do backprojection (2D to 3D) I get that you are using the camera to world matrix. However when doing the projection (3D to 2D) you are still using the camera to world matrix. But should be the world to camera matrix the one applied.

Thanks!

**Comment by Dongjiahua** [comment]
Hi, thanks for your interest. 

When calculating the projection from one view to another view, we use a different approach from the standard projection algorithm. Specifically, we use the ray bundle to get the 3D points, and then project 3D to 2D with the camera matrix (generate_coords_from_directions function). 

Initially we do so to handle different camera types like Fisheye and others, affecting it to be a slower implementation. However, this part's implementation is not necessary now since we just transform every camera to perspective ones in the published code.  You can feel free to change it to the standard projection algorithm.
